### ISSUE TITLE
请问您这个SGM跟opencv实现的有什么区别吗？各有什么优缺点？

### ISSUE THREAD

**Issue by CaptainEven** [ethan-li-coding/SemiGlobalMatching#10]

**Comment by ethan-li-coding** [comment]
这个就是比较原味的sgm，opencv做了一些效率上的优化，这个的主要目的是为了更好的学习sgm，代码会写的比opencv更容易理解

**Comment by CaptainEven** [comment]
@ethan-li-coding 好哒，多谢！

**Comment by CaptainEven** [comment]
@ethan-li-coding 请问您这个版本的SGBM容易做成多线程版本吗？其实，我还是感觉openCV实现的SGBM太慢了，只用到了单核...

**Comment by ethan-li-coding** [comment]
很容易做。opencv其实是做了很多加速了，多线程和SIMD应该都用了

**Comment by CaptainEven** [comment]
SIMD应该有，但是多线程(多核并行)应该没有，因为只有一个核心占用了，其他核心负载很小....
