### ISSUE TITLE
运行效果

### ISSUE THREAD

**Issue by yangh-zzf-itcast** [ethan-li-coding/SemiGlobalMatching#12]
你好作者，我运行了你放在data目录中得测试图像，为什么得到得效果跟你展示得不一样哈，没有修改任何地方。
Reindeer结果
![image](https://user-images.githubusercontent.com/45489193/150122523-d4623700-6923-44a7-adbf-460c00905d6d.png)

**Comment by ethan-li-coding** [comment]
代码里把视差填充关闭了，你在main.cpp里把sgm_option.is_fill_holes = false; 改为 sgm_option.is_fill_holes = true;
