### ISSUE TITLE
代价聚合公式使用初始代价值

### ISSUE THREAD

**Issue by fifoteam** [ethan-li-coding/SemiGlobalMatching#14]
您好，李博士
我们正在打算将sgm放到FPGA中
在您的算法中，计算代价聚合公式中L1 L2 L3 L4时，用到了上一个点的聚合代价值，请问是否可以改为初始代价值
因为用初始代价值方便FPGA实现

**Comment by ethan-li-coding** [comment]
并不推荐，这已经和聚合的理论背道而驰了，动态规划的原理已经被破坏，聚合是在找总代价和最小的那条路径，所以要累加
