### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by ZhangYuanQing99** [ethan-li-coding/SemiGlobalMatching#15]
李老师您好！我在VS2017中运行代码时遇到了一些问题，想向您寻求帮助。
![image](https://user-images.githubusercontent.com/104605736/190640622-2f69a4b5-05af-4d71-9af7-720a804ae896.png)

**Comment by ethan-li-coding** [comment]
图片看不出来问题，2017没有测试过，你可以换vs2019。

**Comment by ZhangYuanQing99** [comment]
谢谢李老师，应该是软件的版本问题，我后来在VS2013中运行成功了。不过我用MiddleBurry2014数据集测试了一下，得到的视差图结果比较差，请问是需要调参数嘛

**Comment by ethan-li-coding** [comment]
视差范围可以调整一下看效果的变化，不过整体来说2014效果是会差一些
