### ISSUE TITLE
Input image were rectified

### ISSUE THREAD

**Issue by ArtlyStyles** [ethan-li-coding/SemiGlobalMatching#3]
Looks like the input image must be rectified. Could you please tell us how to rectify two original camera images?

**Comment by ethan-li-coding** [comment]
(1) if you are working with stereo camera, you should first calibrate your camera by tools, such as matlab and opencv,  then rectifing.
(2) if you jush have two images , you can compute the fundamental matrix by extracting and matching feature points, then rectifing.  

you can do the above two using opencv.
