### ISSUE TITLE
OpenCV-310.dll not found

### ISSUE THREAD

**Issue by Citygity** [ethan-li-coding/SemiGlobalMatching#8]
Did not found OpenCV-310(d).dll in OpenCV-310.rar. could you please share it again.

**Comment by ethan-li-coding** [comment]
Did the antivirus software delete the file? I check the rar, it exists.

**Comment by Citygity** [comment]
Thank you for your reply, I checked it again. There are only there folders :bin, include and lib. 
LIb was downloaded from https://pan.baidu.com/s/1_WD-KdPyDBazEIim7NU3jA

**Comment by ethan-li-coding** [comment]
oh sorry，actually it's name is "opencv_world310.dll" or ""opencv_world310d.dll", in folder bin.

**Comment by Citygity** [comment]
> oh sorry，actually it's name is "opencv_world310.dll" or ""opencv_world310d.dll", in folder bin.

Thanks a lot.
